#!/bin/sh

# Get the current volume
current_volume=$(amixer -D pulse sget Master | grep % | awk '{print $5}' | tr -d '[]%')

# Get the maximum volume
max_volume=$(amixer -D pulse sget Master | grep % | awk '{print $7}' | tr -d '[]%')

# Calculate the volume percentage
volume_percentage=$(echo "scale=2; $current_volume / $max_volume * 100" | bc -l)

# Print the volume percentage
killall dunst
notify-send -i /usr/share/icons/Win11-dark/status/24/volume-level-high.svg " Volume " " $volume_percentage%"
